-- งบประมาณ (เงินงบ & เงินนอก) ส่วน Master
SELECT ALLOCATE_BUDGET_AMOUNT, ACTUAL_BUDGET_AMOUNT, USE_BUDGET_AMOUNT
, ALLOCATE_OFF_BUDGET_AMOUNT, ACTUAL_OFF_BUDGET_AMOUNT, USE_OFF_BUDGET_AMOUNT
FROM T_BUDGET_MASTER 
WHERE YR = 2021;



-- งบประมาณ (เงินงบ & เงินนอก) ลงรายการค่าใช้จ่าย
SELECT SUM(BUDGET_AMOUNT) AS ESTIMATE_BUDGET_AMOUNT
, SUM(ACTUAL_BUDGET_AMOUNT) AS ACTUAL_BUDGET_AMOUNT
, SUM(USE_BUDGET_AMOUNT) AS USE_BUDGET_AMOUNT

, SUM(OFF_BUDGET_AMOUNT) AS ESTIMATE_OFF_BUDGET_AMOUNT
, SUM(USE_OFF_BUDGET_AMOUNT) AS USE_OFF_BUDGET_AMOUNT
FROM T_BUDGET_EXPENSES
WHERE YR = 2021 AND ACTIVE = 1;

-- ประวัติการรับเงินงบประมาณ
SELECT SUM(CASE WHEN BUDGET_TYPE = 1 THEN RECEIVE_BUDGET_AMOUNT ELSE 0.00 END) AS HIS_ESTIMATE_BUDGET_AMOUNT
-- เงินงบประมาณ ส่วนโครงการ
, (SELECT SUM(BUDGET_AMOUNT) FROM T_BUDGET_EXPENSES_PROJECT X WHERE X.ACTIVE = 1 AND X.PROJECT_FOR_TYPE = 1 AND X.YR = 2021) AS PRO_ESTIMATE_BUDGET_AMOUNT

, SUM(CASE WHEN BUDGET_TYPE = 2 THEN RECEIVE_BUDGET_AMOUNT ELSE 0.00 END) AS HIS_RECEIVE_OFF_BUDGET_AMOUNT
-- เงินนอกงบประมาณ ส่วนโครงการ
, (SELECT SUM(OFF_BUDGET_AMOUNT) FROM T_BUDGET_EXPENSES_PROJECT X WHERE X.ACTIVE = 1 AND X.PROJECT_FOR_TYPE = 2 AND X.YR = 2021) AS PRO_ESTIMATE_BUDGET_AMOUNT
FROM T_BUDGET_EXPENSES_RECEIVE A
WHERE YR = 2021 AND ACTIVE = 1;



-- ประวัติการรับเงินประจำงวด
SELECT SUM(CASE WHEN BUDGET_TYPE = 1 THEN RECEIVE_BUDGET_AMOUNT ELSE 0.00 END) AS TOTAL_INCOME_BUDGET_AMOUNT
, (SELECT SUM(BUDGET_AMOUNT) FROM T_OFF_BUDGET_MASTER_INCOME_HISTORY WHERE ACTIVE = 1 AND YR = 2021) AS TOTAL_INCOME_OFF_BUDGET
FROM T_BUDGET_EXPENSES_INCOME WHERE ACTIVE = 1 AND YR = 2021;


-- การใช้จ่ายเงินงบประมาณ
SELECT 
SUM(CASE WHEN BUDGET_TYPE = 1 THEN ALLOCATE_BUDGET_AMOUNT ELSE 0.00 END) +
(SELECT SUM(ALLOCATE_BUDGET_AMOUNT) FROM T_BUDGET_ALLOCATE_EXPENSES_GROUP_HISTORY WHERE YR = 2021 AND ACTIVE = 1 AND ADJUSTMENT_TYPE = 1 AND BUDGET_TYPE = 1) AS TOTAL_ALLOCATE_BUDGET_AMOUNT 
, (SELECT SUM(RESERVE_BUDGET_AMOUNT) FROM T_BUDGET_RESERVE WHERE ACTIVE = 1 AND YR = 2021 AND BUDGET_TYPE = 1) AS TOTAL_RESERVE_BUDGET_AMOUNT

, SUM(CASE WHEN BUDGET_TYPE = 2 THEN ALLOCATE_BUDGET_AMOUNT ELSE 0.00 END) +
ISNULL((SELECT SUM(ALLOCATE_BUDGET_AMOUNT) FROM T_BUDGET_ALLOCATE_EXPENSES_GROUP_HISTORY WHERE YR = 2021 AND ACTIVE = 1 AND ADJUSTMENT_TYPE = 1 AND BUDGET_TYPE = 2), 0) AS TOTAL_ALLOCATE_OFF_BUDGET_AMOUNT 
, (SELECT SUM(RESERVE_BUDGET_AMOUNT) FROM T_BUDGET_RESERVE WHERE ACTIVE = 1 AND YR = 2021 AND BUDGET_TYPE = 2) AS TOTAL_RESERVE_OFF_BUDGET_AMOUNT
FROM T_BUDGET_ALLOCATE_EXPENSES_HISTORY WHERE ACTIVE = 1 AND YR = 2021 AND ADJUSTMENT_TYPE = 1;

-- ตรวจสอบรายการที่ยกเลิก
--SELECT * FROM T_BUDGET_EXPENSES WHERE ACTIVE = -1;
--SELECT * FROM T_BUDGET_EXPENSES_RECEIVE WHERE ACTIVE = -1;
--SELECT * FROM T_BUDGET_EXPENSES_INCOME WHERE ACTIVE = -1;

-- ข้อมูลผลผลิต 

--SELECT * FROM T_BUDGET_EXPENSES_PROJECT WHERE ACTIVE = -1;
--SELECT * FROM T_BUDGET_EXPENSES WHERE ACTIVE = -1;
