
SELECT * FROM T_BUDGET_ALLOCATE WHERE DEP_ID = 1;

SELECT SUM(ALLOCATE_BUDGET_AMOUNT) AS ALLOCATE_BUDGET_AMOUNT
, SUM(USE_BUDGET_AMOUNT) AS USE_BUDGET_AMOUNT
, SUM(ALLOCATE_OFF_BUDGET_AMOUNT) AS ALLOCATE_OFF_BUDGET_AMOUNT
, SUM(USE_OFF_BUDGET_AMOUNT) AS USE_OFF_BUDGET_AMOUNT 
FROM T_BUDGET_ALLOCATE_EXPENSES 
WHERE DEP_ID = 1 AND ACTIVE=  1
AND PLAN_ID = 3
AND PRODUCE_ID = 3
AND ACTIVITY_ID = 1
AND BUDGET_TYPE_ID = 2
AND EXPENSES_GROUP_ID = 23
AND EXPENSES_ID = 39
;


SELECT * FROM T_PLAN_CONFIGURE WHERE ACTIVE = 1;
SELECT * FROM T_PRODUCE_CONFIGURE WHERE ACTIVE = 1;
SELECT * FROM T_ACTIVITY_CONFIGURE WHERE ACTIVE = 1;
SELECT * FROM T_BUDGET_TYPE WHERE ACTIVE = 1;
SELECT * FROM T_EXPENSES_GROUP WHERE ACTIVE = 1 AND BUDGET_TYPE_ID = 1;
SELECT * FROM T_EXPENSES_ITEM WHERE ACTIVE = 1 AND EXPENSES_GROUP_ID = 5;


SELECT *
FROM T_BUDGET_REPORTED_USE_EXPENSES_HISTORY 
WHERE DEP_ID = 1 AND ACTIVE=  1
GROUP BY BUDGET_TYPE;

SELECT BUDGET_TYPE
, SUM(ALLOCATE_BUDGET_AMOUNT) AS ALLOCATE_BUDGET_AMOUNT 
FROM T_BUDGET_ALLOCATE_EXPENSES_HISTORY WHERE DEP_ID = 1 AND ACTIVE = 1 AND ADJUSTMENT_TYPE = 1
GROUP BY BUDGET_TYPE;

-- SELECT *
-- FROM T_BUDGET_ALLOCATE_EXPENSES WHERE DEP_ID = 1 AND ACTIVE=  1;
-- SELECT * FROM T_DEPARTMENT WHERE DEP_ID = 1;
SELECT * FROM T_DEPARTMENT_AUTHORIZE;