---- ล้างข้อมูล Template คำของบประมาณ
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_TEMPLATE];
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_TEMPLATE_DEPARTMENT_AUTHORIZE];
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_TEMPLATE_EXPENSES];
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_TEMPLATE_YR_AUTHORIZE];
--TRUNCATE TABLE [dbo].[T_USER_FAVORITE_BUDGET_TEMPLATE];

-- ล้างข้อมูล คำของบประมาณ
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_MASTER];
--TRUNCATE TABLE [dbo].[T_BUDGET_REQUEST_DETAIL];

-- ล้างข้อมูล การรับเงินงบประมาณจาก รัฐบาล
TRUNCATE TABLE [dbo].[T_BUDGET_MASTER];
TRUNCATE TABLE [dbo].[T_BUDGET_EXPENSES];
TRUNCATE TABLE [dbo].[T_OFF_BUDGET_MASTER_INCOME_HISTORY];
TRUNCATE TABLE [dbo].[T_BUDGET_EXPENSES_PROJECT];
TRUNCATE TABLE [dbo].[T_BUDGET_EXPENSES_RECEIVE];
TRUNCATE TABLE [dbo].[T_BUDGET_EXPENSES_INCOME];

-- ล้างข้อมูลจัดสรรงบประมาณ ลงไปยังหน่วยงาน
TRUNCATE TABLE [dbo].[T_BUDGET_ALLOCATE];
TRUNCATE TABLE [dbo].[T_BUDGET_ALLOCATE_EXPENSES];
TRUNCATE TABLE [dbo].[T_BUDGET_ALLOCATE_EXPENSES_HISTORY];

-- ล้างข้อมูลการรายงานผลการใช้จ่ายของหน่วยงาน
TRUNCATE TABLE [dbo].[T_BUDGET_REPORTED_USE_EXPENSES_HISTORY];

-- ล้างข้อมูล กันเงิน & เบิกจ่าย
TRUNCATE TABLE [dbo].[T_BUDGET_RESERVE];
TRUNCATE TABLE [dbo].[T_BUDGET_RESERVE_HISTORY];
TRUNCATE TABLE [dbo].[T_BUDGET_RESERVE_WITHDRAWAL];
TRUNCATE TABLE [dbo].[T_BUDGET_RESERVE_WITHDRAWAL_HISTORY];